import Stripe from 'stripe';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join } from 'path';

/**
 * NanoAuth Stripe Synchronizer 🌊
 * Automatically creates/updates products and generates src/lib/plans.ts
 */

// 1. Loading Environment
const envPath = join(process.cwd(), '.env');
const envContent = existsSync(envPath) ? readFileSync(envPath, 'utf8') : '';
const STRIPE_SECRET_KEY = envContent.match(/STRIPE_SECRET_KEY=(.*)/)?.[1]?.trim();

if (!STRIPE_SECRET_KEY) {
    console.error('❌ Error: STRIPE_SECRET_KEY not found in .env');
    process.exit(1);
}

const stripe = new Stripe(STRIPE_SECRET_KEY, {
    apiVersion: '2026-03-25.dahlia',
});

const DEFAULT_PLANS = [
    { name: 'starter', price: 1999, limits: { projects: 3 } },
    { name: 'pro', price: 4999, limits: { projects: 10 } }
];

async function sync() {
    console.log('🛰️ Starting Stripe Synchronization...');
    const activePlans: any[] = [];

    for (const planDef of DEFAULT_PLANS) {
        console.log(`\n🔍 Checking plan: ${planDef.name.toUpperCase()}`);

        // Find product
        let product;
        const products = await stripe.products.list({ limit: 100 });
        product = products.data.find(p => p.name.toLowerCase() === planDef.name.toLowerCase() && p.active);

        if (!product) {
            console.log(`✨ Product not found. Creating "${planDef.name}"...`);
            product = await stripe.products.create({
                name: planDef.name.toUpperCase(),
                description: `NanoAuth ${planDef.name} Subscription`,
                metadata: { type: 'nanoauth_plan', plan_key: planDef.name }
            });
        }

        // Find or create price
        let price;
        const prices = await stripe.prices.list({ product: product.id, active: true });
        price = prices.data[0];

        if (!price) {
            console.log(`💸 Price not found for ${planDef.name}. Creating $${planDef.price / 100}/mo...`);
            price = await stripe.prices.create({
                product: product.id,
                unit_amount: planDef.price,
                currency: 'usd',
                recurring: { interval: 'month' },
            });
        }

        activePlans.push({
            name: planDef.name,
            priceId: price.id,
            limits: planDef.limits
        });

        console.log(`✅ Plan Synced: ${price.id}`);
    }

    // Generate src/lib/plans.ts
    const filePath = join(process.cwd(), 'src/lib/plans.ts');
    const content = `/**
 * Stripe Plans - Source of Truth 💳
 * This file is automatically generated by scripts/sync-stripe.ts
 */

export const plans = ${JSON.stringify(activePlans, null, 2)};
`;

    writeFileSync(filePath, content);
    console.log(`\n🎉 Success! Updated: ${filePath}`);
}

sync().catch(console.error);
