/**
 * Stripe Plans - Source of Truth 💳
 * This file is automatically generated by scripts/sync-stripe.ts
 */

export const plans = [
  {
    "name": "starter",
    "priceId": "price_1TMURqEdsiW8bjaefVUKKaUn",
    "limits": {
      "projects": 3
    }
  },
  {
    "name": "pro",
    "priceId": "price_1TMURrEdsiW8bjaebQpZJuEu",
    "limits": {
      "projects": 10
    }
  }
];
